### ISSUE TITLE
Unknown exception error

### ISSUE THREAD

**Issue by behzaadh** [simulkade/PhreeqcMatlab#2]
Hi Ehsan,

Why do I receive an "Unknown exception" error when my code reaches 934 in the PhreeqcRM class? this line calls function in C shared library as shown in the following line
status = calllib('libphreeqcrm','RM_RunFile', obj.id, workers, initial_phreeqc, utility, chem_name)

**Comment by simulkade** [comment]
This runs an input Phreeqc file. See if you can run the specified input file in phreeqc itself. [This version](https://www.hydrochemistry.eu/ph3/index.html) from Tony Appelo is the one that I use myself.

**Comment by behzaadh** [comment]
The problem comes from the compiler. Installing Visual C++ Redistributable for VC 2015 does not help. The solution is that [C++ tools from visual studio installer](https://devblogs.microsoft.com/cppblog/announcing-visual-c-build-tools-2015-standalone-c-tools-for-build-environments/) must be installed.
